# Generated by Django 2.0.5 on 2018-05-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='alternates_new',
            field=models.ManyToManyField(blank=True, related_name='_ingredient_alternates_new_+', to='masterdata.Ingredient'),
        ),
    ]
