# Generated by Django 2.0.5 on 2018-05-22 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_ingredient_isalternate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='alternates_new',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='alternates',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='alternates',
            field=models.ManyToManyField(blank=True, to='masterdata.Ingredient'),
        ),
    ]
