# Generated by Django 2.0.5 on 2018-05-23 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_auto_20180522_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.Category'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.Group'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.State'),
        ),
    ]
