# Generated by Django 2.0.5 on 2018-05-24 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0008_auto_20180524_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='shelflife',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
