# Generated by Django 2.0.5 on 2018-05-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0009_auto_20180524_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='alternates_str',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='finalspec_str',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
