# Generated by Django 2.0.5 on 2018-06-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0010_auto_20180529_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'size',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='size',
            field=models.ManyToManyField(blank=True, null=True, to='masterdata.Size'),
        ),
    ]
