# Generated by Django 2.0.5 on 2018-06-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0013_ingredient_size_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='size',
            new_name='size_finalspec',
        ),
    ]
