# Generated by Django 2.0.5 on 2018-06-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0016_auto_20180612_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientConversion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.CharField(max_length=100)),
                ('preparation', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('form', models.CharField(max_length=100)),
                ('cup_per_unit', models.FloatField(max_length=100)),
                ('createdate', models.DateTimeField(auto_now_add=True)),
                ('lastmodified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ingredent_conversion',
                'ordering': ('ingredient',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='ingredientconversion',
            unique_together={('ingredient', 'preparation', 'size', 'category', 'form')},
        ),
    ]
