# Generated by Django 2.0.5 on 2018-06-14 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0017_auto_20180613_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.CharacteristicType'),
        ),
    ]
