# Generated by Django 2.0.5 on 2018-06-27 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0019_auto_20180627_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterdata.Group'),
        ),
        migrations.AlterModelTable(
            name='pattern',
            table='pattern',
        ),
    ]
