# Generated by Django 2.0.5 on 2018-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0020_auto_20180627_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pattern',
            name='pattern_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pattern',
            name='target_pattern',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
